### ISSUE TITLE
Change text on buttons for creating cohorts and cohort groups

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/openmrs-module-cohort#10]
Based on how things are usually labelled in OpenMRS, I would propose the following changes:
- Change `Create Cohorts` to `Create Cohort` (i.e., remove the 's')
- Change `Create Group Cohort` to `Create Cohort Group`

![screen shot 2016-08-02 at 1 30 57 pm](https://cloud.githubusercontent.com/assets/3488986/17325696/a414c77a-58b5-11e6-9cde-5a9d0d6bd828.png)

**Comment by bholagabbar** [comment]
Fixed in commit 318e1dfcd1692643059932c7bb50fc0f035a6856
