### ISSUE TITLE
Add Cohort Type - No character limit is available on Name field

### ISSUE THREAD

**Issue by zohaibihs** [OpenSRP/openmrs-module-cohort#11]
Add Cohort Type - No character limit is available on Name field (There should be a character limit of 20 characters on text fields). 

![image](https://cloud.githubusercontent.com/assets/20788534/17326251/8a6b8912-58c9-11e6-9ee5-7ad5918d18ae.png)

**Comment by zohaibihs** [comment]
Kindly let me know the reason of closing this bug.

**Comment by bholagabbar** [comment]
Clubbed here https://github.com/OpenSRP/openmrs-module-cohort/issues/15
