### ISSUE TITLE
Add Cohort Program - No character limit is available on Name field

### ISSUE THREAD

**Issue by zohaibihs** [OpenSRP/openmrs-module-cohort#14]
Add Cohort Program - No character limit is available on Name field (There should be a character limit of 20 characters on text fields).

**Comment by zohaibihs** [comment]
Kindly let me know the reason of closing this bug.

**Comment by bholagabbar** [comment]
Clubbed here https://github.com/OpenSRP/openmrs-module-cohort/issues/15
