### ISSUE TITLE
Add punctuation to readme description on repo

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/openmrs-module-cohort#2]
> The purpose is to manage cohort related data cohorts, cohort types cohort attributes cohort attribute types cohort members cohort member attribute cohort member attribute type Using REST to allow external system integration with cohort module Cohort Management can be performed in two ways Simple Cohorts for single entities Cohorts including groups or collections like households

The description above is missing all punctuation, which makes it unreadable. Please add punctuation.

**Comment by bholagabbar** [comment]
Sure I'll fix this up. Also, this module does not have a 'description'. The one that appears beside the module. I don't have the rights to add that so maybe someone who does (the module creator) could add that

**Comment by bholagabbar** [comment]
I issued a Pull request for this (https://github.com/OpenSRP/openmrs-module-cohort/pull/4). Please see the description and if it fits, feel free to merge it or we can discuss changes here

**Comment by cafootitt** [comment]
Closed with #4
