### ISSUE TITLE
Fix 404 error when clicking on link in Cohort Module

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/openmrs-module-cohort#3]
![screen shot 2016-08-02 at 9 42 22 am](https://cloud.githubusercontent.com/assets/3488986/17319318/9245a296-5895-11e6-92d9-7495b4a8388a.png)

Clicking on the `Manage Cohorts and Metadata` option in the screen above leads to an error page:

`HTTP Status 404 -`

`type Status report`

`message`

`description The requested resource is not available.`

`Apache Tomcat/6.0.39`

One option is to just remove this option from the menu, as the user is able to reach the same page by the Cohort Dashboard > Management route

**Comment by bholagabbar** [comment]
Fixed in [this](https://github.com/OpenSRP/openmrs-module-cohort/commit/028d8b42ec73bc3cca90dd955ad3a257b6929aac) commit. Can we close the issue?

**Comment by maimoonak** [comment]
Thanks Shreyan for quickly resolving this. When an issue is resolved add labled "resolved" and QA would verify and close the issue for next release. For this issue I added the label from top right corner in palette.

**Comment by bholagabbar** [comment]
@maimoonak  Sorry I closed the issue without reading your comment :P Works fine
