### ISSUE TITLE
Click to Openmrs logo  – exception report is appearing

### ISSUE THREAD

**Issue by zohaibihs** [OpenSRP/openmrs-module-cohort#32]
Click to Openmrs logo  –exception report is appearing.(Crash)

![image](https://cloud.githubusercontent.com/assets/20788534/17357696/8372f79a-5977-11e6-863f-60f22a6a0635.png)

**Comment by bholagabbar** [comment]
Fixed in https://github.com/OpenSRP/openmrs-module-cohort/commit/759ba7aef3951be60fa9baa547042abad9eb1082
