### ISSUE TITLE
Enter Cohort Detail – clicking on the “save and skip” 

### ISSUE THREAD

**Issue by zohaibihs** [OpenSRP/openmrs-module-cohort#35]
Enter Cohort Detail – clicking on the “save and skip” button is not allowing the duplicate record entry. (High)

**Comment by bholagabbar** [comment]
Not allowing duplicate record entries meaning? Which particular duplicate entries are not being allowed? Name or something else?

**Comment by zohaibihs** [comment]
Dashboard>> click to Create cohorts >>  Enter Cohort Detail – Same cohort name should be allow (High) example >> same cohort name should not allowed - like IT person record create 7 time 

![same cohort name](https://cloud.githubusercontent.com/assets/20788534/17505361/0ec09f9a-5e1a-11e6-84ff-3686c83b72c3.png)

Search cohorts >> cohort name >> IT person >> 7 record show >> same cohort name should not allowed 

![search](https://cloud.githubusercontent.com/assets/20788534/17505419/864fcd2e-5e1a-11e6-8d0c-8b156f13c738.png)

**Comment by bholagabbar** [comment]
@zohaibihs Basically duplicate members in cohorts are not allowed yes? Fixed in commit https://github.com/OpenSRP/openmrs-module-cohort/commit/a31d0a6b2cdfe52e56e5c4d717e8c3b7ec6adc66 and https://github.com/OpenSRP/openmrs-module-cohort/commit/a160bd5efeebd921349f7a41ec76d4dc25b3b641

**Comment by zohaibihs** [comment]
Yes, it should not be allowed.

**Comment by bholagabbar** [comment]
@zohaibihs yeah fixed
