### ISSUE TITLE
Add Cohort Attribute - Internal error is appearing on SelectCohort Attribute type

### ISSUE THREAD

**Issue by zohaibihs** [OpenSRP/openmrs-module-cohort#36]
Add Cohort Attribute – Internal error is appearing on Select Cohort Attribute type(Value: Cannot handle type []. Please add a module to handle this type.)(UI Suggestion – High)

![image](https://cloud.githubusercontent.com/assets/20788534/17359986/9b451f00-5982-11e6-9ebb-54a44cae83dc.png)

**Comment by bholagabbar** [comment]
Uhh this is not actually an internal error. What this simply means to say is that it can not handle type [] or something that is _blank_ in the dropdown. Can you suggest an alternative message that says please select a value and a blank value will not be accepted?

@maimoonak @zohaibihs

**Comment by zohaibihs** [comment]
It should be "please select a value".
