### ISSUE TITLE
Add Cohort attribute - Click to next button exception report is appearing.

### ISSUE THREAD

**Issue by zohaibihs** [OpenSRP/openmrs-module-cohort#37]
Add Cohort attribute – Click to next button exception report is appearing.(Crash).

![image](https://cloud.githubusercontent.com/assets/20788534/17360027/d5af90b2-5982-11e6-8119-d2a440173507.png)

![image](https://cloud.githubusercontent.com/assets/20788534/17360022/c78cf8da-5982-11e6-8741-55f907be1f78.png)

**Comment by bholagabbar** [comment]
Not facing this on my system. @maimoonak Any clue why this is happening? I installed my complete setup from scratch. Running core 1.11.7, _htmlformentry-3.2-SNAPSHOT_, _webservices.rest-2.15-SNAPSHOT.062bbe_ with no other addition modules.

**Comment by bholagabbar** [comment]
Screenshot on my system after clicking next as you mentioned:

![Uploading Capture.PNG…]()

**Comment by bholagabbar** [comment]
Again, possible deployment problem
