### ISSUE TITLE
Dashboard - search record (IT person)- after appearing the search result(s) 

### ISSUE THREAD

**Issue by zohaibihs** [OpenSRP/openmrs-module-cohort#39]
Dashboard - search record (IT person)- after appearing the search result(s) - click on the add member button - exception report is appearing.(Crash)

![image](https://cloud.githubusercontent.com/assets/20788534/17360112/4c8a2486-5983-11e6-9b2e-2d70b0675fc2.png)

![image](https://cloud.githubusercontent.com/assets/20788534/17360058/0b9aa5a4-5983-11e6-8867-26ce205f02ce.png)

**Comment by bholagabbar** [comment]
@maimoonak Could you check this? This isn't happening on my system..
![capture](https://cloud.githubusercontent.com/assets/11693595/17391866/2331260c-5a37-11e6-8979-bab79761f828.PNG)

**Comment by maimoonak** [comment]
@bholagabbar This could be because you added few columns manually in DB. Can you try this module on a fresh installation. And if it does not work maybe we need to add column to liquibase.

**Comment by bholagabbar** [comment]
Yes but I did a fresh installation of the module after adding the
column..also adding that column wasn't related to cpatients I guess

**Comment by maimoonak** [comment]
ok. Then let me cleanup the existing cohort data and do fresh installation
