### ISSUE TITLE
Add cohort role – caption should be “Add Cohort role”

### ISSUE THREAD

**Issue by zohaibihs** [OpenSRP/openmrs-module-cohort#41]
Add cohort role – caption should be “Add Cohort role” (High).

![image](https://cloud.githubusercontent.com/assets/20788534/17360338/8ea5b2d0-5984-11e6-989f-99788866a48f.png)

**Comment by bholagabbar** [comment]
Pull Request: https://github.com/OpenSRP/openmrs-module-cohort/pull/43
