### ISSUE TITLE
Edit Cohort Type – Edit Success message

### ISSUE THREAD

**Issue by zohaibihs** [OpenSRP/openmrs-module-cohort#42]
Edit Cohort Type – Edit Success message after Editing a form should be appeared in green color.(UI Suggestion - Low)

![image](https://cloud.githubusercontent.com/assets/20788534/17362373/48eb47f0-598e-11e6-964c-84542a608656.png)

**Comment by bholagabbar** [comment]
Fixed in [this](https://github.com/OpenSRP/openmrs-module-cohort/commit/509ca4160ee00027ef5d5b719954e97b78799bbc) commit. It seems that the edit functionality itself had not been added. Did that too
