### ISSUE TITLE
Correct heading on Edit Cohort Type page

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/openmrs-module-cohort#7]
See below. It is supposed to say `Edit Cohort Type` instead of `Edit Cohort Role`

![screen shot 2016-08-02 at 1 09 11 pm](https://cloud.githubusercontent.com/assets/3488986/17325098/7142a0b8-58b2-11e6-8834-083de3bae112.png)

To replicate, go to the Cohort Type page, then select a cohort type to edit.

**Comment by bholagabbar** [comment]
Letting issue #23 be
