### ISSUE TITLE
Change Cohort Role to Cohort Member Role

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/openmrs-module-cohort#8]
If I'm understanding this correctly, the role feature is for a cohort member, not for the cohort itself, so should we change this to say `Cohort Member Role` instead of `Cohort Role`?

![screen shot 2016-08-02 at 1 15 02 pm](https://cloud.githubusercontent.com/assets/3488986/17325262/54cb229c-58b3-11e6-8a7e-00014f26ee3e.png)

**Comment by maimoonak** [comment]
Yeh thats true. @bholagabbar plz change labels for this. Though in DB and in API its fine o leave these as it is.

**Comment by cafootitt** [comment]
Ok, have updated the title to reflect this.

**Comment by bholagabbar** [comment]
fixed in commit https://github.com/OpenSRP/openmrs-module-cohort/commit/08ec934cd12545bf07909cfeb935098870dce429
