### ISSUE TITLE
Fix error when clicking on Create Group Cohort

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/openmrs-module-cohort#9]
When I click on `Create Group Cohort` from the main Dashboard page, I get this error page:

![screen shot 2016-08-02 at 1 29 18 pm](https://cloud.githubusercontent.com/assets/3488986/17325631/4572bfd8-58b5-11e6-8e99-fb1fcfbf5d37.png)

**Comment by bholagabbar** [comment]
Issue with deployment. Works locally!
